apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
spec:
  progressDeadlineSeconds: 3600
  replicas: 2
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: userapiforaks
          image: acrforapi.azurecr.io/aksuserapikubernetes-image:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: userapi
